/* ---------- Data Kedai Segara (Laporan Stock September · CV. Dapur Rumah Rasa) ---------- */
var DATA_SEGARA = [
  ['Freezer Protein', [
    ["AS", "Ayam Suwir", "Porsi"],
    ["TK", "Topping Kwetiau", "Porsi"],
    ["TM", "Topping Mbakmoy", "Porsi"],
    ["AJ", "Ayam Jamur", "Porsi"],
    ["DGM", "Dada Gurih Manis", "Porsi"],
    ["PGM", "Paha Gurih Manis", "Porsi"],
    ["P", "Paha", "Porsi"],
    ["D", "Dada", "Porsi"],
    ["Syp", "Sayap Goreng", "Porsi"],
    ["Daging", "Daging Slice", "Porsi"],
    ["C", "Cumi", "Porsi"],
    ["K", "Kulit", "Porsi"],
    ["L", "Lidah", "Porsi"],
    ["LGS", "Lidah Goreng Segara", "Porsi"],
    ["TP", "Teri Pete", "Porsi"],
    ["TNG", "Topping Nasi Gila", "Porsi"],
    ["PTA", "Pete Add On", "Porsi"],
    ["PT", "Pete", "Porsi"],
    ["B", "Bagor", "Porsi"],
    ["DS", "Daging Sambal HIjau", "Porsi"],
    ["BC", "Sambal Baby Cumi", "Porsi"],
    ["TA", "Tahu Aci", "Pack"],
    ["Cr", "Cireng", "Porsi"],
  ]],
  ['Freezer Bumbu', [
    ["SB", "Sambal Bawang", "Pack"],
    ["S.terasi", "Sambal Terasi", "Pack"],
    ["SK", "Sambal Kuning", "Pack"],
    ["SP", "Sambal Petis", "Pack"],
    ["ST", "Sambal Terong", "Pack"],
    ["BS", "Bumbu Segara", "Pack"],
    ["BL", "Bumbu Lidah", "Pack"],
    ["Serundeng", "Bumbu Serundeng", "Pack"],
    ["BK", "Bumbu Kwetiau", "Pack"],
    ["GM", "Gorengan Mbakmoy", "Pack"],
    ["BUL", "Bumbu Ungkep Lidah", "Pack"],
    ["BNG", "Bumbu Nasi Gila", "Pack"],
    ["BT", "Bumbu Teri", "Pack"],
    ["BMG", "Bumbu Mie Goreng Jawa", "Pack"],
  ]],
  ['Freezer Roti & Juice', [
    ["RotiB", "Roti Bakar", "Pack"],
    ["RotiA", "Roti Angsle", "Pack"],
    ["Sirsak", "Sirsak Juice", "Pack"],
    ["SM", "Manggo Juice", "Pack"],
    ["Berries", "Mix Berries", "Pack"],
  ]],
  ['Flavourful Drink', [
    ["M", "Mineral", "Botol"],
    ["AT", "Air Tahu", "Botol"],
    ["Polaris", "Soda Polaris", "Kaleng"],
    ["ZD", "Zoda Water", "Kaleng"],
    ["Kaleng", "Lhychee Kaleng", "Kaleng"],
    ["Apple", "Apple Juice Diamond", "Pcs"],
    ["DHT", "Syrup Dht", "Jug"],
    ["Butter", "Dripp Butterschotch", "Botol"],
    ["Pandan", "Dripp Pandan", "Botol"],
    ["Lhychee", "Dripp Lhychee", "Botol"],
    ["Sun", "Sunquick Manggo", "Botol"],
    ["Lemon", "Ecolate Lemongrass", "Pack"],
    ["Winter", "Ecolate Wintermelon Tea", "Pack"],
    ["Kopi", "Kopi", "Pack"],
    ["LT", "Lemon Tea", "Pack"],
  ]],
  ['Barang Kering (Dairy + Plant Base Milk)', [
    ["UHT", "Diamond Milk", "Pcs"],
    ["Cara1", "Sun Cara 1L", "Pcs"],
    ["Evap", "Susu Evaporasi", "Kaleng"],
    ["SKM", "Susu Kental Manis Carnation", "Pcs"],
    ["Oatside", "Oatside Milk", "Pcs"],
    ["Cashew", "Cashew Milk", "Pcs"],
    ["Cara200", "Sun Cara 200Ml", "Pcs"],
    ["Creamer", "Max Creamer", "Pcs"],
    ["Milo", "Milo", "Pcs"],
    ["Keju", "Keju", "Pcs"],
    ["MB", "Minyak Beku", "Pcs"],
    ["MC", "Kunci Mas", "Pcs"],
  ]],
  ['Bahan Dasar + Kecap', [
    ["Gula", "Gula", "Pack"],
    ["Garam", "Garam", "Pack"],
    ["BR", "Bumbu Racik", "Pack"],
    ["BG", "Bumbu Gule", "Pack"],
    ["T", "Terasi", "Pcs"],
    ["GulaH", "Gula Halus", "Pack"],
    ["Knor", "Knorr", "Pack"],
    ["RR", "Raja Rasa", "Botol"],
    ["Tipparos", "Kecap Ikan Tipparos", "Botol"],
    ["Maggi", "Kecap Maggi", "Botol"],
    ["SS", "Saus Sambal", "Pack"],
    ["Tomat", "Saus Tomat", "Pack"],
  ]],
  ['Bahan Snack / Dessert + Tepung', [
    ["Beras", "Tepung Beras Bola", "Pack"],
    ["Ketan", "Tepung Ketan", "Pack"],
    ["Maizena", "Tepung Maizena", "Pack"],
    ["Terigu", "Tepung Terigu", "Pack"],
    ["Tapioka", "Tepung Tapioka", "Pack"],
    ["TT", "Tepung Telur", "Pack"],
    ["Urai", "Mie Urai", "Pack"],
    ["Plain", "Nurtijel Plain", "Pack"],
    ["Sagu", "Sagu Mutiara", "Pack"],
    ["Nata", "Nata Decoco", "Pack"],
    ["Hijau", "Pewarna Hijau", "Btl"],
    ["Pink", "Pewarna Pink", "Btl"],
    ["V", "Vanilli", "Btl"],
  ]],
  ['Cleaning Supplies + Utensils', [
    ["Ps.ukS", "Plastik Sampah S", "Lbr", "1 Pack Isi 10 pcs"],
    ["Ps.ukM", "Plastik Sampah M", "Lbr", "1 Pack Isi 10 pcs"],
    ["Ps.ukL", "Plastik Sampah L", "Lbr", "1 Pack Isi 10 pcs"],
    ["Ps.ukXL", "Plastik Sampah XL", "Lbr", "1 Pack Isi 10 pcs"],
    ["Paper", "Thermal Paper", "Roll"],
    ["Eko", "Ekonomi", "Pcs"],
    ["Ice", "Cup Ice", "Pack"],
    ["SoupXS", "Plastik Soup XS", "Pack"],
    ["Tmeja", "Tissue Meja", "Pack"],
    ["TWC", "Tissue Toilet", "Pack"],
    ["Tbm", "Take Away Box M", "Pack"],
    ["CupS", "Cup Sambal", "Pack"],
    ["Bm24", "Plastik Bima uk24", "Pack"],
    ["Tbs", "Take Away Box S", "Pack"],
    ["TbL", "Take Away Bocx L", "Pack"],
    ["Bm28", "Plastik Bima uk.28", "Pack"],
    ["Sdt", "Sedotan", "Pack"],
    ["Bm15", "Plastik Bima uk.15", "Pack"],
    ["Sumpit", "Sumpit", "Pack"],
    ["Sbb", "Sendok Bebek", "Pack"],
    ["2in1", "2in1 Sendok", "Pack"],
    ["Hot", "Cup Hot", "Pack"],
    ["SoupM", "Plastik Soup M", "Roll"],
    ["SoupL", "Plastik Soup L", "Pack"],
    ["Lakban", "Lakban Segara", "Roll"],
  ]],
];
